"""Tailoring specification models for job-specific CV rendering.

A TailoringSpec controls how the CV is rendered for a specific job:
section ordering, entry emphasis/omission, profile override,
and page budget. Keywords are metadata for skill analysis.
"""

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field


class KeywordHighlight(BaseModel):
    """A keyword or phrase to emphasize in the tailored CV.

    Weight controls emphasis level: 0 = omit, 1 = normal, 2 = strong.
    """

    model_config = ConfigDict(populate_by_name=True)

    term: str = Field(description="Keyword or phrase to highlight")
    weight: float = Field(
        1.0,
        ge=0.0,
        le=2.0,
        description="Emphasis level: 0=omit, 1=normal, 2=strong",
    )


class SectionDirective(BaseModel):
    """Per-section rendering control for the tailored CV.

    Determines whether a section is included and its position in the output.
    """

    model_config = ConfigDict(populate_by_name=True)

    section_name: str = Field(description="Section name matching CV section headers")
    include: bool = Field(
        True,
        description="Whether to include this section in the output",
    )
    position: int = Field(
        description="Render order position (0=first, ascending)",
    )


class EntryEmphasis(BaseModel):
    """Per-entry emphasis control for the tailored CV.

    Weight controls visibility: 0 = omit entry, 1 = normal, 2 = highlight.
    """

    model_config = ConfigDict(populate_by_name=True)

    entry_id: str = Field(
        description="Stable entry identifier (e.g., 'work-yahoo-kgs-2023')",
    )
    weight: float = Field(
        1.0,
        ge=0.0,
        le=2.0,
        description="Emphasis level: 0=omit, 1=normal, 2=highlight",
    )
    reason: str = Field(
        "",
        description="Why this emphasis was chosen (for auditability)",
    )


class TailoringSpec(BaseModel):
    """Complete specification for rendering a job-tailored CV.

    Generated by the cv-tailoring skill from job description analysis.
    Consumed by render_tailored_latex() to produce a page-constrained,
    role-specific LaTeX document.
    """

    model_config = ConfigDict(populate_by_name=True)

    job_title: str = Field(description="Target job title")
    company: str = Field(
        "",
        description="Target company name",
    )
    job_id: str = Field(
        "",
        description="Job posting identifier (LinkedIn job ID, requisition number, or slug). Used in output filenames to distinguish multiple applications to the same company.",
    )
    section_order: list[SectionDirective] = Field(
        description="Ordered list of section rendering directives",
    )
    entry_emphasis: list[EntryEmphasis] = Field(
        [],
        description="Per-entry emphasis overrides (entries not listed use weight=1)",
    )
    keywords: list[KeywordHighlight] = Field(
        [],
        description="Keywords to highlight in the output",
    )
    profile_override: str = Field(
        "",
        description="Custom profile/summary text replacing the default summary",
    )
    max_pages: int = Field(
        2,
        ge=1,
        le=3,
        description="Maximum page count for the tailored CV",
    )
